//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleBaseEntities2 : DbContext
    {
        public VehicleBaseEntities2()
            : base("name=VehicleBaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bike> Bike { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Motorbike> Motorbike { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
    }
}
